In [36]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding

# Sample data
reviews = [
    'nice food', 'amazing restaurant', 'too good', 'just loved it!',
    'will go again', 'horrible food', 'never go there', 'poor service',
    'poor quality', 'needs improvement'
]

# Sentiments (1 for positive, 0 for negative)
sentiment = np.array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

# Vocabulary size
vocab_size = 30

# One-hot encoding of reviews
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print("Encoded reviews:", encoded_reviews)

# Padding sequences
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print("Padded reviews:", padded_reviews)

# Embedding parameters
embedded_vector_size = 5

# Define the model
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=embedded_vector_size, input_length=max_length, name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Ensure the model is explicitly built
model.build(input_shape=(None, max_length))

# Display model summary
model.summary()


Encoded reviews: [[18, 25], [18, 12], [8, 21], [26, 29, 21], [17, 22, 2], [6, 25], [6, 22, 28], [2, 14], [2, 21], [28, 6]]
Padded reviews: [[18 25  0  0]
 [18 12  0  0]
 [ 8 21  0  0]
 [26 29 21  0]
 [17 22  2  0]
 [ 6 25  0  0]
 [ 6 22 28  0]
 [ 2 14  0  0]
 [ 2 21  0  0]
 [28  6  0  0]]


Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ (None, 4, 5)                │             150 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_8 (Flatten)                  │ (None, 20)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_8 (Dense)                      │ (None, 1)                   │              21 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 171 (684.00 B)

 Trainable params: 171 (684.00 B)

 Non-trainable params: 0 (0.00 B)

In [37]:
model.fit(X, y, epochs=50, verbose=0)

In [38]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 533ms/step - accuracy: 1.0000 - loss: 0.6079


1.0